name: tracebuddy_app
version: 0.0.1
description: Web app for the TraceBuddy ray tracer.
authors:
- Frederik Leonhardt <frederik.leonhardt@gmail.com>
- Michael Frey <asakash117@gmail.com>

dependencies:
  browser: ">=0.10.0 <0.11.0"
  tracebuddy:
    path: ../trace-buddy
  web_ui: ">=0.4.28 <0.5.0"
  source_maps: ">=0.9.0 <0.10.0" # source_maps 0.10.0 breaks something
