name:  TraceBuddy
description:  A raytracer to render implicit functions.

dependencies:
  browser: "0.3.5+1"
  vector_math: ">=0.9.3"
  unittest: ">=0.3.5"
  benchmark_harness: ">=1.0.0 <2.0.0"
  web_ui: "0.3.2"