name:  TraceBuddy
description:  A raytracer to render implicit functions.

dependencies:
  browser: ">=0.7.6 <0.8.0"
  vector_math: ">=1.3.5 <1.3.6"
  unittest: ">=0.7.6 <0.8.0"
  benchmark_harness: ">=1.0.2 <1.0.3"
  web_ui: ">=0.4.21 <0.4.22"