name:  TraceBuddy
description:  A raytracer to render implicit functions.
authors:
- Frederik Leonhardt <frederik.leonhardt@gmail.com>
- Michael Frey <asakash117@gmail.com>

dependencies:
  browser: ">=0.10.0 <0.11.0"
  vector_math: ">=1.3.5 <1.5.0"
  math_expressions: ">=0.0.8 <0.1.0"
  web_ui: ">=0.4.27 <0.5.0"

dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
  benchmark_harness: ">=1.0.2 <1.1.0"