name:  TraceBuddy
description:  A sample application

#dependencies:
#  js: any
#  unittest: any

dependencies:
  vector_math: 0.9.2
  unittest: any
  benchmark_harness: ">=1.0.0 <2.0.0"
  web_ui: any