name:  TraceBuddy
description:  A raytracer to render implicit functions.

dependencies:
  browser: ">=0.4.3 <0.4.4"
  vector_math: ">=0.9.7 <0.9.8"
  unittest: ">=0.4.4 <0.4.5"
  benchmark_harness: ">=1.0.2 <1.0.3"
  web_ui: ">=0.4.3 <0.4.4"