name:  tracebuddy
version: 0.0.1
description:  TraceBuddy is a ray tracer designed to render implicit functions.
authors:
- Frederik Leonhardt <frederik.leonhardt@gmail.com>
- Michael Frey <asakash117@gmail.com>

dependencies:
  vector_math: '>=1.4.4 <2.0.0'
  math_expressions: '>=0.3.0-dev'
  image: '>=1.1.25 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  benchmark_harness:
    git: https://github.com/dart-lang/benchmark_harness
