name:  tracebuddy
version: 0.0.1
description:  TraceBuddy is a raytracer to render implicit functions.
authors:
- Frederik Leonhardt <frederik.leonhardt@gmail.com>
- Michael Frey <asakash117@gmail.com>

dependencies:
  vector_math: ">=1.3.5 <1.5.0"
  math_expressions: ">=0.1.0 <0.2.0"

dev_dependencies:
  unittest: ">=0.10.0 <0.12.0"
  benchmark_harness: ">=1.0.2 <1.1.0"